version: '2'

services:
    db:
        image: mysql
        ports:
            - 3306:3306
        volumes:
            - ${DB_DATA}:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    php:
        build: php7-fpm
        ports:
            - 9000:9000
        volumes:
            - ${CODE_DATA}:/var/www/symfony
        links:
            - db:mysqldb
        environment:
            SERVER_HOST: ${SERVER_HOST}

    nginx:
        build: nginx
        ports:
            - 80:80
            - 443:443
        links:
            - php
        volumes_from:
            - php
            
    elk:
        build: elk
        ports:
            - 81:5601
        volumes_from:
            - php
            - nginx
