version: '2'

services:
    db:
        image: mysql
        ports:
            - 3306:3306
        volumes:
            - ./data/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    php:
        build: php7-fpm
        ports:
            - 9000:9000
        links:
            - db:mysqldb

    node:
        build: node
        volumes:
            - ./node/gulp:/project
            - /project/build
            - /project/.sass-cache
            - ./data/node/bower:/project/build/bower
            - ./data/node/modules:/project/node_modules

    nginx:
        build: nginx
        ports:
            - 80:80
        links:
            - php
        volumes_from:
            - php
            
    elk:
        build: elk
        ports:
            - 81:5601
        volumes_from:
            - php
            - nginx
