symfony:
    build: symfony/
    volumes:
        - ./code:/var/www
        - ./var/logs/symfony:/var/www/app/logs
    tty: true

db:
    image: mysql:5.5
    ports:
        - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: symfony
        MYSQL_USER: symfony
        MYSQL_PASSWORD: symfony

php:
    build: php-fpm/
    expose:
        - 9000:9000
    links:
        - db
    volumes_from:
        - symfony
    environment:
        APP_SERVER_NAME: symfony.dev

nginx:
    build: nginx/
    ports:
        - 8080:80
    links:
        - php
        - redis
    volumes_from:
        - symfony
    volumes:
            - ./var/logs/nginx/:/var/log/nginx
    environment:
        <APP_SERVER_NAME>: symfony.dev

npm:
    build: npm/
    volumes_from:
        - symfony
    tty: true

redis:
    image: redis:3.0.5
