version: '3.4'

services:
    php:
        build: php7-fpm
        image: "core23/symfony-php:${TAG:-latest}"
        volumes:
            - ./test-data:/var/www/symfony
        links:
            - mysql:mysqldb

    nginx:
        build: nginx
        image: "core23/symfony-nginx:${TAG:-latest}"
        links:
            - php
        ports:
            - 0:80
        volumes:
            - ./test-data:/var/www/symfony
            - nginx-log:/var/log/nginx
        environment:
            NGINX_HOST: ${NGINX_HOST}

    mysql:
        image: mysql:5
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    elk:
        build: elk
        image: "core23/symfony-elk:${TAG:-latest}"
        depends_on:
            - nginx
            - php
        volumes:
            - ./test-data:/var/www/symfony
            - nginx-log:/var/log/nginx:ro

volumes:
    nginx-log:
